version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__DefaultConnection=host=dbpostgre;Port=5432;database=in_catalog;user id=postgres;password=1234
    ports:
      - "7410:80"
      - "7411:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__DefaultConnection=host=dbpostgre;Port=5432;database=in_order;user id=postgres;password=1234
    ports:
      - "7416:80"
      - "7417:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - AuthSettings__Google__ClientId=255995720827-0a61ksg8g1pfijcfeap7poknf319jshl.apps.googleusercontent.com
      - AuthSettings__Google__ClientSecret=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
      - ConnectionStrings__DefaultConnection=host=dbpostgre;Port=5432;database=identityserver;user id=postgres;password=1234
    ports:
      - "7407:80"
      - "7408:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  subscription.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__DefaultConnection=host=dbpostgre;Port=5432;database=in_subscription;user id=postgres;password=1234
    ports:
      - "7418:80"
      - "7419:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  web.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__UrlAuthority=http://identityserver
      - AppSettings__UrlIssuer=http://identityserver/
      - AppSettings__Urls__Identity=http://identityserver
      - AppSettings__Urls__Catalog=http://catalog.api
      - AppSettings__Urls__Inspiration=http://inspiration:8080
      - AppSettings__Urls__Testimonial=http://testimonial:8080
      - AppSettings__Urls__Exhibition=http://exhibition:8080
      - AppSettings__Urls__Analytic=http://analytic:8080
      - AppSettings__Urls__Notification=http://notification:8080
      - AppSettings__Urls__Ordering=http://ordering.api
      - AppSettings__Urls__Subscription=http://subscription.api
      - AppSettings__Urls__GrpcCatalog=http://catalog.api:81
      - AppSettings__Urls__GrpcOrdering=http://ordering.api:81
      - AppSettings__Urls__GrpcSubscription=http://subscription.api:81
      - AppSettings__Urls__GrpcIdentity=http://identityserver:81
      - HealthChecksUI__HealthChecks__0__Name=Identity Server Check
      - HealthChecksUI__HealthChecks__0__Uri=http://identityserver/hc
      - HealthChecksUI__HealthChecks__1__Name=Gateway Check
      - HealthChecksUI__HealthChecks__1__Uri=http://web.gateway/hc
      - HealthChecksUI__HealthChecks__2__Name=Catalog Check
      - HealthChecksUI__HealthChecks__2__Uri=http://catalog.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
    ports:
      - "7405:80"
